title: Mountainview Web Design
description:
markdown: kramdown
highlighter: rouge
permalink: /:title/
baseurl:
exclude: [bower.json, README.md]
email: adam@mountainview-webdesign.com
analytics: UA-31980509-9
